name: "Test"

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # https://crontab.guru/#30_5,17_*_*_*
    - cron: "30 5,17 * * *"
  pull_request:
  push:

jobs:
  cache:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        cache: ["br4ch1st0chr0n3-flakes"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v17
        with:
          # about GITHUB_TOKEN
          # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret

          # environment variables
          # https://docs.github.com/en/actions/learn-github-actions/environment-variables
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            substituters =  https://cache.nixos.org/ https://hydra.iohk.io https://haskell-language-server.cachix.org
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= haskell-language-server.cachix.org-1:juFfHrwkOxqIOZShtC4YC1uT1bBcq2RSvC7OMKx0Nz8=
      - uses: cachix/cachix-action@v10
        with:
          name: br4ch1st0chr0n3-flakes
          # If you chose API tokens for write access OR if you have a private cache
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Check codium flake
        run: |
          cd codium
          nix flake check
      - name: Push inputs to cachix
        run: |
          # https://docs.cachix.org/pushing#flakes

          nix flake archive --json \
            | jq -r '.path,(.inputs|to_entries[].value.path)' \
            | cachix push ${{ matrix.cache }}
      - name: Push devshell to cachix
        run: |
          nix develop --profile dev-profile
          cachix push ${{ matrix.cache }} dev-profile
