name: "Caching"

on:
  schedule:
    # https://crontab.guru/#30_5,17_*_*_*
    # * is a special character in YAML so you have to quote this string
    - cron: "0 0 * * *"
  pull_request:
  push:

jobs:
  caching:
    name: Build on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, macos-11, macos-12]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            substituters = https://cache.nixos.org/ https://nix-community.cachix.org https://hydra.iohk.io https://haskell-language-server.cachix.org https://br4ch1st0chr0n3.cachix.org
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= haskell-language-server.cachix.org-1:juFfHrwkOxqIOZShtC4YC1uT1bBcq2RSvC7OMKx0Nz8= br4ch1st0chr0n3.cachix.org-1:o1FA93L5vL4LWi+jk2ECFk1L1rDlMoTH21R1FHtSKaU=
      - uses: cachix/cachix-action@v10
        with:
          name: ${{ secrets.CACHIX_CACHE }}
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      # - name: Use cache
      #   run: cachix use ${{ secrets.CACHIX_CACHE }}
      - name: Push flakes to cachix
        run: CACHIX_CACHE=${{ secrets.CACHIX_CACHE }} nix run
      # - name: Format .nix files
      #   run: nix fmt **/*.nix

# It'd be nice to support these platforms:
# x86_64-darwin
# aarch64-darwin
# aarch64-linux
# i686-linux
# x86_64-linux

# GitHub only supports these:
# https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
# x86_64-linux
# x86_64-darwin

# environment variables
# https://docs.github.com/en/actions/learn-github-actions/environment-variables
# you can get runner.arch == ARM if you use a self-hosted runner
# https://docs.github.com/en/actions/learn-github-actions/contexts#example-contents-of-the-runner-context

# about GITHUB_TOKEN
# https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret

# push flakes to cachix
# https://docs.cachix.org/pushing#flakes
